### ISSUE TITLE
ValueError: md5 of GeoLite2-City.mmdb.gz doesn't match the signature

### ISSUE THREAD

**Issue by Richzendy** [kalekseev/django-geoipdb-loader#2]
Hi,

I'm switching my app to python3 and i getting this when i run **python manage.py download_geoipdb** 

```
Raven is not configured (logging is disabled). Please see the documentation for more information.

Traceback (most recent call last):

  File "manage.py", line 22, in <module>

    execute_from_command_line(sys.argv)

  File "/home/user/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line

    utility.execute()

  File "/home/user/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/home/user/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/home/user/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute

    output = self.handle(*args, **options)

  File "/home/user/lib/python3.5/site-packages/geoipdb_loader/management/commands/download_geoipdb.py", line 45, in handle

    logger=Logger(self.style, self.stdout),

  File "/home/user/lib/python3.5/site-packages/geoipdb_loader/__init__.py", line 111, in download

    _download_file(**entry)

  File "/home/user/lib/python3.5/site-packages/geoipdb_loader/__init__.py", line 73, in _download_file

    'md5 of %s doesn\'t match the signature.' % downloaded_file

ValueError: md5 of /home/user/app/geoipdb/GeoLite2-City.mmdb.gz doesn't match the signature
```
Some change from maxmind's website or was python3?

**Comment by lalviarez** [comment]
@Richzendy try updating to latest version

**Comment by Richzendy** [comment]
Thank you @lalviarez , is working now.
